// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20251223123359_FixInvoiceLineItemsForeignKeys")]
    partial class FixInvoiceLineItemsForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Supplier",
                            NormalizedName = "SUPPLIER"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("backend.Models.Inventory.Brand", b =>
                {
                    b.Property<int>("Brand_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Brand_ID"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Brand_ID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Brand_ID = 1,
                            BrandName = "Pilot",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 2,
                            BrandName = "Bic",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 3,
                            BrandName = "Parker",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 4,
                            BrandName = "Fiber Castel",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 5,
                            BrandName = "Staedtler",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 6,
                            BrandName = "Faber-Castell",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 7,
                            BrandName = "Pentel",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 8,
                            BrandName = "Sharpie",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 9,
                            BrandName = "Expo",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 10,
                            BrandName = "Crayola",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 11,
                            BrandName = "Prismacolor",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 12,
                            BrandName = "Moleskine",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 13,
                            BrandName = "Oxford",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 14,
                            BrandName = "Mead",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Brand_ID = 15,
                            BrandName = "Ticonderoga",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("backend.Models.Inventory.Category", b =>
                {
                    b.Property<int>("Category_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_ID"));

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Category_ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Category_ID = 1,
                            Category_Name = "Writing Instruments",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Category_ID = 2,
                            Category_Name = "Art Supplies",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Category_ID = 3,
                            Category_Name = "Notebooks & Paper",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Category_ID = 4,
                            Category_Name = "Office Supplies",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Category_ID = 5,
                            Category_Name = "Classroom Tools",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Category_ID = 6,
                            Category_Name = "Storage & Organization",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Category_ID = 7,
                            Category_Name = "Technology Accessories",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Category_ID = 8,
                            Category_Name = "Science & Lab Supplies",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("backend.Models.Inventory.Inventory", b =>
                {
                    b.Property<int>("Inventory_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Inventory_ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inventory_Clerk")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Inventory_Number")
                        .HasColumnType("int");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int>("Total_Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Inventory_ID");

                    b.HasIndex("Inventory_Clerk");

                    b.HasIndex("Product_ID");

                    b.ToTable("Inventory", (string)null);

                    b.HasData(
                        new
                        {
                            Inventory_ID = 1,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "1",
                            Inventory_Number = 1001,
                            Product_ID = 1,
                            Total_Quantity = 150,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 2,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "2",
                            Inventory_Number = 1002,
                            Product_ID = 2,
                            Total_Quantity = 75,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 3,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "1",
                            Inventory_Number = 1003,
                            Product_ID = 3,
                            Total_Quantity = 200,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 4,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "2",
                            Inventory_Number = 1004,
                            Product_ID = 4,
                            Total_Quantity = 120,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 5,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "1",
                            Inventory_Number = 1005,
                            Product_ID = 5,
                            Total_Quantity = 80,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 6,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "2",
                            Inventory_Number = 1006,
                            Product_ID = 6,
                            Total_Quantity = 300,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 7,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "1",
                            Inventory_Number = 1007,
                            Product_ID = 7,
                            Total_Quantity = 50,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 8,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "2",
                            Inventory_Number = 1008,
                            Product_ID = 8,
                            Total_Quantity = 30,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 9,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "1",
                            Inventory_Number = 1009,
                            Product_ID = 9,
                            Total_Quantity = 40,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 10,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "2",
                            Inventory_Number = 1010,
                            Product_ID = 10,
                            Total_Quantity = 25,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 11,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "1",
                            Inventory_Number = 1011,
                            Product_ID = 11,
                            Total_Quantity = 60,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 12,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "2",
                            Inventory_Number = 1012,
                            Product_ID = 12,
                            Total_Quantity = 100,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 13,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "1",
                            Inventory_Number = 1013,
                            Product_ID = 13,
                            Total_Quantity = 200,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 14,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "2",
                            Inventory_Number = 1014,
                            Product_ID = 14,
                            Total_Quantity = 15,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Inventory_ID = 15,
                            Created_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Inventory_Clerk = "1",
                            Inventory_Number = 1015,
                            Product_ID = 15,
                            Total_Quantity = 25,
                            Updated_At = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("backend.Models.Inventory.Product", b =>
                {
                    b.Property<int>("Product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_ID"));

                    b.Property<int>("Brand_ID")
                        .HasColumnType("int");

                    b.Property<int>("Category_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Variant_ID")
                        .HasColumnType("int");

                    b.HasKey("Product_ID");

                    b.HasIndex("Brand_ID");

                    b.HasIndex("Category_ID");

                    b.HasIndex("Variant_ID");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Product_ID = 1,
                            Brand_ID = 1,
                            Category_ID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smooth writing gel ink pen with 0.7mm tip",
                            Product_Code = "PILOT-G2-07-BLK",
                            Product_Name = "Pilot G2 0.7 Gel Pen - Black",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 1
                        },
                        new
                        {
                            Product_ID = 2,
                            Brand_ID = 2,
                            Category_ID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic ballpoint pen with smooth writing",
                            Product_Code = "BIC-CRYSTAL-BLK",
                            Product_Name = "Bic Crystal Ballpoint Pen - Black",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 2
                        },
                        new
                        {
                            Product_ID = 3,
                            Brand_ID = 7,
                            Category_ID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fast-drying gel pen with precise 0.5mm tip",
                            Product_Code = "PENTEL-ENERGEL-05-BLU",
                            Product_Name = "Pentel EnerGel 0.5mm Gel Pen - Blue",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 3
                        },
                        new
                        {
                            Product_ID = 4,
                            Brand_ID = 8,
                            Category_ID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permanent marker with fine point for detailed work",
                            Product_Code = "SHARPIE-FINE-BLK",
                            Product_Name = "Sharpie Fine Point Permanent Marker - Black",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 4
                        },
                        new
                        {
                            Product_ID = 5,
                            Brand_ID = 9,
                            Category_ID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Low-odor dry erase marker for whiteboards",
                            Product_Code = "EXPO-DRY-ERASE-BLK",
                            Product_Name = "Expo Dry Erase Marker - Black",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 5
                        },
                        new
                        {
                            Product_ID = 6,
                            Brand_ID = 15,
                            Category_ID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium #2 pencil with soft graphite",
                            Product_Code = "TICONDEROGA-2-PENCIL",
                            Product_Name = "Ticonderoga #2 Pencil",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 6
                        },
                        new
                        {
                            Product_ID = 7,
                            Brand_ID = 10,
                            Category_ID = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic 24-count box of crayons",
                            Product_Code = "CRAYOLA-24-CRAYONS",
                            Product_Name = "Crayola 24-Count Crayons",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 7
                        },
                        new
                        {
                            Product_ID = 8,
                            Brand_ID = 11,
                            Category_ID = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Professional quality colored pencils",
                            Product_Code = "PRISMACOLOR-12-PENCILS",
                            Product_Name = "Prismacolor Premier Colored Pencils - 12 Count",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 8
                        },
                        new
                        {
                            Product_ID = 9,
                            Brand_ID = 5,
                            Category_ID = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fine-tip markers in assorted colors",
                            Product_Code = "STAEDTLER-12-MARKERS",
                            Product_Name = "Staedtler Triplus Fineliner - 12 Count",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 9
                        },
                        new
                        {
                            Product_ID = 10,
                            Brand_ID = 6,
                            Category_ID = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality colored pencils for art projects",
                            Product_Code = "FABER-CASTELL-12-PENCILS",
                            Product_Name = "Faber-Castell Colored Pencils - 12 Count",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 10
                        },
                        new
                        {
                            Product_ID = 11,
                            Brand_ID = 12,
                            Category_ID = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hardcover notebook with ruled pages",
                            Product_Code = "MOLESKINE-CLASSIC-NOTEBOOK",
                            Product_Name = "Moleskine Classic Notebook - Large",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 11
                        },
                        new
                        {
                            Product_ID = 12,
                            Brand_ID = 13,
                            Category_ID = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "200-page spiral notebook with college ruled paper",
                            Product_Code = "OXFORD-SPIRAL-NOTEBOOK",
                            Product_Name = "Oxford Spiral Notebook - College Ruled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 12
                        },
                        new
                        {
                            Product_ID = 13,
                            Brand_ID = 14,
                            Category_ID = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "100-sheet composition book with wide ruled pages",
                            Product_Code = "MEAD-COMPOSITION-BOOK",
                            Product_Name = "Mead Composition Book - Wide Ruled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 13
                        },
                        new
                        {
                            Product_ID = 14,
                            Brand_ID = 2,
                            Category_ID = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard size staples for heavy duty staplers",
                            Product_Code = "STAPLES-HEAVY-DUTY",
                            Product_Name = "Heavy Duty Staples - 5000 Count",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 14
                        },
                        new
                        {
                            Product_ID = 15,
                            Brand_ID = 2,
                            Category_ID = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assorted sizes paper clips for document organization",
                            Product_Code = "PAPER-CLIPS-MIXED",
                            Product_Name = "Mixed Size Paper Clips - 100 Count",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_ID = 15
                        });
                });

            modelBuilder.Entity("backend.Models.Inventory.Variant", b =>
                {
                    b.Property<int>("Variant_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Variant_ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Variant_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Variant_ID");

                    b.ToTable("Variants");

                    b.HasData(
                        new
                        {
                            Variant_ID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "Single Pack"
                        },
                        new
                        {
                            Variant_ID = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "12-Pack"
                        },
                        new
                        {
                            Variant_ID = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "3-Pack"
                        },
                        new
                        {
                            Variant_ID = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "4-Pack"
                        },
                        new
                        {
                            Variant_ID = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "4-Pack Assorted Colors"
                        },
                        new
                        {
                            Variant_ID = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "12-Pack"
                        },
                        new
                        {
                            Variant_ID = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "24-Count Box"
                        },
                        new
                        {
                            Variant_ID = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "12-Count Set"
                        },
                        new
                        {
                            Variant_ID = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "12-Count Assorted"
                        },
                        new
                        {
                            Variant_ID = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "12-Count Set"
                        },
                        new
                        {
                            Variant_ID = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "Large (5\" x 8.25\")"
                        },
                        new
                        {
                            Variant_ID = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "200 Pages"
                        },
                        new
                        {
                            Variant_ID = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "100 Sheets"
                        },
                        new
                        {
                            Variant_ID = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "5000 Count Box"
                        },
                        new
                        {
                            Variant_ID = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variant_Name = "100 Count Mixed Sizes"
                        });
                });

            modelBuilder.Entity("backend.Models.InvoiceModel.Invoice", b =>
                {
                    b.Property<int>("Invoice_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Invoice_ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Invoice_Clerk")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Invoice_Number")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Invoice_ID");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("Invoice_Clerk");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("backend.Models.LineItems.InvoiceLineItems", b =>
                {
                    b.Property<int>("LineItem_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineItem_ID"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("Invoice_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Invoice_ID1")
                        .HasColumnType("int");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Sub_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UOM_ID")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Unit_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Unit_Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("isPercentageDiscount")
                        .HasColumnType("bit");

                    b.HasKey("LineItem_ID");

                    b.HasIndex("Invoice_ID");

                    b.HasIndex("Invoice_ID1");

                    b.HasIndex("Product_ID");

                    b.HasIndex("UOM_ID");

                    b.ToTable("InvoiceLineItems", (string)null);
                });

            modelBuilder.Entity("backend.Models.LineItems.RestockLineItems", b =>
                {
                    b.Property<int>("LineItem_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineItem_ID"));

                    b.Property<int>("Base_UOM_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Base_Unit_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Base_Unit_Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Batch_ID")
                        .HasColumnType("int");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.HasKey("LineItem_ID");

                    b.HasIndex("Base_UOM_ID");

                    b.HasIndex("Batch_ID");

                    b.HasIndex("Product_ID");

                    b.ToTable("RestockLineItems", (string)null);
                });

            modelBuilder.Entity("backend.Models.PersonalDetails", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Address = "123 Admin St, Cityville",
                            CompanyName = "Prince Educational Supply",
                            ConcurrencyStamp = "8d5e6f7a-1b2c-3d4e-5f6a-7b8c9d0e1f2a",
                            Email = "admin@prince.edu",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Administrator",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@PRINCE.EDU",
                            NormalizedUserName = "ADMIN",
                            Notes = "System Administrator Account",
                            PasswordHash = "$2a$12$jp5zIIJOL8xuwDJ8iFQ71eCo8SkyYUe.EzycyKo9x8avU63OE./DK",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7c4c8c0a-9b3a-4e5f-9d1c-1a2b3c4d5e6f",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            Address = "456 Employee Rd, Cityville",
                            CompanyName = "Prince Educational Supply",
                            ConcurrencyStamp = "0e1f2a3b-4c5d-6e7f-8a9b-0c1d2e3f4a5b",
                            Email = "employee@prince.edu",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = true,
                            NormalizedEmail = "EMPLOYEE@PRINCE.EDU",
                            NormalizedUserName = "EMPLOYEE",
                            Notes = "Inventory Manager",
                            PasswordHash = "$2a$12$ftZOEZ3bCuHwb8sY3q4TK.9842WEhzdptOPQdDGYnfyFt0Wr.Fhbi",
                            PhoneNumber = "2345678901",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9d0e1f2a-3b4c-5d6e-7f8a-9b0c1d2e3f4a",
                            TwoFactorEnabled = false,
                            UserName = "employee"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            Address = "789 Supplier Ave, Townsville",
                            CompanyName = "Educational Supplies Inc.",
                            ConcurrencyStamp = "2a3b4c5d-6e7f-8a9b-0c1d-2e3f4a5b6c7d",
                            Email = "supplier@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Smith",
                            LockoutEnabled = true,
                            NormalizedEmail = "SUPPLIER@EXAMPLE.COM",
                            NormalizedUserName = "SUPPLIER",
                            Notes = "Main supplier of stationery",
                            PasswordHash = "$2a$12$ycj3WiWbM50s0umHkb3ZmuX9BHbrfhmZm8Ps58grA/E2GdF2BG1Ge",
                            PhoneNumber = "3456789012",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1f2a3b4c-5d6e-7f8a-9b0c-1d2e3f4a5b6c",
                            TwoFactorEnabled = false,
                            UserName = "supplier"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            Address = "101 Customer Blvd, Villageville",
                            CompanyName = "Johnson Elementary School",
                            ConcurrencyStamp = "4c5d6e7f-8a9b-0c1d-2e3f-4a5b6c7d8e9f",
                            Email = "customer@example.com",
                            EmailConfirmed = true,
                            FirstName = "Robert",
                            LastName = "Johnson",
                            LockoutEnabled = true,
                            NormalizedEmail = "CUSTOMER@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMER",
                            Notes = "Regular customer - monthly orders",
                            PasswordHash = "$2a$12$qg9Dg6MBwphaDdYWImxO7O8pwjz9NWz28r9hGiCWnDLtVa0ynK9W2",
                            PhoneNumber = "4567890123",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3b4c5d6e-7f8a-9b0c-1d2e-3f4a5b6c7d8e",
                            TwoFactorEnabled = false,
                            UserName = "customer"
                        });
                });

            modelBuilder.Entity("backend.Models.RestockModel.Restock", b =>
                {
                    b.Property<int>("Restock_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Restock_ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Restock_Clerk")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Restock_Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Restock_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Restock_ID");

                    b.HasIndex("Restock_Clerk");

                    b.ToTable("Restock", (string)null);
                });

            modelBuilder.Entity("backend.Models.RestockModel.RestockBatch", b =>
                {
                    b.Property<int>("Batch_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Batch_ID"));

                    b.Property<int>("Batch_Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Restock_ID")
                        .HasColumnType("int");

                    b.Property<string>("Supplier_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Batch_ID");

                    b.HasIndex("Restock_ID");

                    b.HasIndex("Supplier_ID");

                    b.ToTable("RestockBatch", (string)null);
                });

            modelBuilder.Entity("backend.Models.Unit.Product_UOM", b =>
                {
                    b.Property<int>("Product_UOM_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_UOM_Id"));

                    b.Property<int>("Conversion_Factor")
                        .HasColumnType("int");

                    b.Property<int>("LineItem_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Parent_UOM_ID")
                        .HasColumnType("int");

                    b.Property<int>("UOM_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Unit_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Product_UOM_Id");

                    b.HasIndex("LineItem_ID");

                    b.HasIndex("Parent_UOM_ID");

                    b.HasIndex("UOM_ID");

                    b.ToTable("Product_UOM", (string)null);
                });

            modelBuilder.Entity("backend.Models.Unit.UnitOfMeasure", b =>
                {
                    b.Property<int>("uom_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("uom_ID"));

                    b.Property<string>("uom_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("uom_ID");

                    b.ToTable("UnitOfMeasure");

                    b.HasData(
                        new
                        {
                            uom_ID = 1,
                            uom_Name = "PIECES"
                        },
                        new
                        {
                            uom_ID = 2,
                            uom_Name = "PADS"
                        },
                        new
                        {
                            uom_ID = 3,
                            uom_Name = "SETS"
                        },
                        new
                        {
                            uom_ID = 4,
                            uom_Name = "BOXES"
                        },
                        new
                        {
                            uom_ID = 5,
                            uom_Name = "BUNDLES"
                        },
                        new
                        {
                            uom_ID = 6,
                            uom_Name = "ROLLS"
                        },
                        new
                        {
                            uom_ID = 7,
                            uom_Name = "GALLON"
                        },
                        new
                        {
                            uom_ID = 8,
                            uom_Name = "PACKS"
                        },
                        new
                        {
                            uom_ID = 9,
                            uom_Name = "TUBES"
                        },
                        new
                        {
                            uom_ID = 10,
                            uom_Name = "CARTOONS"
                        },
                        new
                        {
                            uom_ID = 11,
                            uom_Name = "CASE"
                        },
                        new
                        {
                            uom_ID = 12,
                            uom_Name = "REAMS"
                        });
                });

            modelBuilder.Entity("backend.Models.Users.DeletedUsers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeletedUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("backend.Models.PersonalDetails", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("backend.Models.PersonalDetails", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.PersonalDetails", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("backend.Models.PersonalDetails", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Inventory.Inventory", b =>
                {
                    b.HasOne("backend.Models.PersonalDetails", "PersonalDetails")
                        .WithMany()
                        .HasForeignKey("Inventory_Clerk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Models.Inventory.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PersonalDetails");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("backend.Models.Inventory.Product", b =>
                {
                    b.HasOne("backend.Models.Inventory.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("Brand_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Models.Inventory.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Category_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Models.Inventory.Variant", "Variant")
                        .WithMany()
                        .HasForeignKey("Variant_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("backend.Models.InvoiceModel.Invoice", b =>
                {
                    b.HasOne("backend.Models.PersonalDetails", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Models.PersonalDetails", "Clerk")
                        .WithMany()
                        .HasForeignKey("Invoice_Clerk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Clerk");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("backend.Models.LineItems.InvoiceLineItems", b =>
                {
                    b.HasOne("backend.Models.InvoiceModel.Invoice", "Invoices")
                        .WithMany()
                        .HasForeignKey("Invoice_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Models.InvoiceModel.Invoice", null)
                        .WithMany("LineItems")
                        .HasForeignKey("Invoice_ID1");

                    b.HasOne("backend.Models.Inventory.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Models.Unit.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UOM_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Invoices");

                    b.Navigation("Product");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("backend.Models.LineItems.RestockLineItems", b =>
                {
                    b.HasOne("backend.Models.Unit.UnitOfMeasure", "BaseUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("Base_UOM_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Models.RestockModel.RestockBatch", "RestockBatch")
                        .WithMany("RestockLineItems")
                        .HasForeignKey("Batch_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Inventory.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaseUnitOfMeasure");

                    b.Navigation("Product");

                    b.Navigation("RestockBatch");
                });

            modelBuilder.Entity("backend.Models.RestockModel.Restock", b =>
                {
                    b.HasOne("backend.Models.PersonalDetails", "Clerk")
                        .WithMany()
                        .HasForeignKey("Restock_Clerk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Clerk");
                });

            modelBuilder.Entity("backend.Models.RestockModel.RestockBatch", b =>
                {
                    b.HasOne("backend.Models.RestockModel.Restock", "Restock")
                        .WithMany("RestockBatches")
                        .HasForeignKey("Restock_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.PersonalDetails", "Supplier")
                        .WithMany()
                        .HasForeignKey("Supplier_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Restock");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("backend.Models.Unit.Product_UOM", b =>
                {
                    b.HasOne("backend.Models.LineItems.RestockLineItems", "RestockLineItem")
                        .WithMany("ProductUOMs")
                        .HasForeignKey("LineItem_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Unit.UnitOfMeasure", "ParentUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("Parent_UOM_ID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("backend.Models.Unit.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UOM_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentUnitOfMeasure");

                    b.Navigation("RestockLineItem");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("backend.Models.InvoiceModel.Invoice", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("backend.Models.LineItems.RestockLineItems", b =>
                {
                    b.Navigation("ProductUOMs");
                });

            modelBuilder.Entity("backend.Models.RestockModel.Restock", b =>
                {
                    b.Navigation("RestockBatches");
                });

            modelBuilder.Entity("backend.Models.RestockModel.RestockBatch", b =>
                {
                    b.Navigation("RestockLineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
